name: dev-intelligent-text-processing-service

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    volumes:
      - ./webapp/src:/app/src
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
