name: intelligent-text-processing-service

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - llm
  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
