name: dev-intelligent-text-processing-service

services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - llm
    volumes:
      - ./webapp/src:/app/src
  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./llm/src:/app/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
